CollectionsManager/Models/Collection.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CollectionsManager.Models;

public class Collection
{
  [Range(1, int.MaxValue, ErrorMessage = "A Category must be chosen")]
  public int CollectionId { get; set; }

  [Required(ErrorMessage = "This is a required field!")]
  public string Name { get; set; }
  public string Description { get; set; }

  public string ImageUrl { get; set; }
  public List<Item> Items { get; set; }
}

CollectionsManager/Controllers/CollectionsController.cs
using Microsoft.AspNetCore.Mvc;
using CollectionsManager.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Threading.Tasks;

namespace CollectionsManager.Controllers
{
  public class CollectionsController : Controller
  {
    private readonly CollectionsManagerContext _db;

    public CollectionsController(CollectionsManagerContext db)
    {
      _db = db;
    }
    public async Task<IActionResult> Index(string searchString)
    {
      IQueryable<Collection> model = from m in _db.Collections
                                     select m;

      if (!String.IsNullOrEmpty(searchString))
      {
        model = model.Where(s => s.Name!.Contains(searchString));
      }
      return View(await model.OrderBy(e => e.Name).ToListAsync());
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public ActionResult Create(Collection collection)
    {
      _db.Collections.Add(collection);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      Collection thisCollection = _db.Collections.FirstOrDefault(collection => collection.CollectionId == id);
      return View(thisCollection);
    }
    [HttpPost]
    public ActionResult Edit(Collection collection)
    {
      _db.Collections.Update(collection);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      Collection thisCollection = _db.Collections.FirstOrDefault(collection => collection.CollectionId == id);
      return View(thisCollection);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Collection thisCollection = _db.Collections.FirstOrDefault(collection => collection.CollectionId == id);
      _db.Collections.Remove(thisCollection);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id, string searchString)
    {
      Collection thisCollection = _db.Collections
          .Include(collection => collection.Items.OrderBy(e => e.Name))
          .FirstOrDefault(collection => collection.CollectionId == id);

      if (!String.IsNullOrEmpty(searchString))
      {
        thisCollection.Items = thisCollection.Items.Where(item => item.Name.Contains(searchString)).OrderBy(e => e.Name).ToList();
      }
      ViewBag.Sum = thisCollection.Items.Sum(i => i.Value);
      ViewBag.CollectionId = id;
      ViewBag.SearchString = searchString;

      return View(thisCollection);
    }


  }
}

CollectionsManager/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using CollectionsManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CollectionsManager.Controllers
{
  public class ItemsController : Controller
  {
    private readonly CollectionsManagerContext _db;
    public ItemsController(CollectionsManagerContext db)
    {
      _db = db;
    }


    public async Task<IActionResult> Index(string searchString)
    {
      IQueryable<Item> model = from m in _db.Items.Include(item => item.Collection)
                               select m;

      if (!string.IsNullOrEmpty(searchString))
      {
        model = model.Where(s => s.Name!.Contains(searchString));
        ViewBag.Title = $"{searchString}";
      }
      ViewBag.Title = "All Items";
      return View(await model.OrderBy(e => e.Name).ToListAsync());
    }

    [HttpGet("/items/create/")]
    public ActionResult Create()
    {
      Dictionary<string, object> model = new() {
        {"Item", new Item()},
        {"CollectionSelect", new SelectList(_db.Collections, "CollectionId", "Name")},
        {"TodaysDate", DateTime.Now.ToString("dd-MM-yyyy")},
        {"Tags", _db.Tags.ToList()},
        {"Action", "Create"}
      };
      return View(model);
    }

    [HttpPost]
    public ActionResult Create(Item item, List<int> TagIds)
    {
      if (item.CollectionId == 0)
      {
        return RedirectToAction("Create");
      }

      _db.Items.Add(item);
      _db.SaveChanges();

      if (TagIds != null && TagIds.Any())
      {
        foreach (var tagId in TagIds)
        {
          _db.ItemTagJoinEntities.Add(new ItemTagJoinEntity
          {
            ItemId = item.ItemId,
            TagId = tagId
          });
        }
        _db.SaveChanges();
      }

      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Item thisItem = _db.Items
                          .Include(item => item.Collection)
                          .Include(item => item.ItemTagJoinEntities)
                          .ThenInclude(join => join.Tag)
                          .FirstOrDefault(item => item.ItemId == id);
      return View(thisItem);
    }

    public ActionResult Edit(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      Dictionary<string, object> model = new() {
        {"Item", thisItem},
        {"CollectionSelect", new SelectList(_db.Collections, "CollectionId", "Name")},
        {"TodaysDate", DateTime.Now.ToString("dd-MM-yyyy")},
        {"Tags", _db.Tags.ToList()},
        {"Action", "Edit"}
      };
      return View(model);
    }

    [HttpPost]
    public ActionResult Edit(Item item, List<int> TagIds)
    {
      _db.Items.Update(item);
      List<ItemTagJoinEntity> entities = _db.ItemTagJoinEntities
      .Where((entity) => entity.ItemId == item.ItemId).ToList();
      foreach (ItemTagJoinEntity entity in entities)
      {
        _db.ItemTagJoinEntities.Remove(entity);
      }
      foreach (var tagId in TagIds)
      {

        _db.ItemTagJoinEntities.Add(new ItemTagJoinEntity
        {
          ItemId = item.ItemId,
          TagId = tagId
        });
      }
      _db.SaveChanges();

      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      return View(thisItem);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Item thisItem = _db.Items.FirstOrDefault(item => item.ItemId == id);
      _db.Items.Remove(thisItem);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTag(int id)
    {
      Item item = _db.Items.FirstOrDefault(items => items.ItemId == id);
      Dictionary<string, object> model = new()
      {
        {"item", item},
        {"selectList", new SelectList(_db.Tags, "TagId", "Name")}
      };
      return View(model);
    }

    [HttpPost]
    public ActionResult AddTag(Item item, int tagId)
    {
#nullable enable
      ItemTagJoinEntity? itemTagJoinEntity = _db.ItemTagJoinEntities
      .FirstOrDefault(join => (join.TagId == tagId && join.ItemId == item.ItemId));
#nullable disable
      if (itemTagJoinEntity == null && tagId != 0)
      {
        _db.ItemTagJoinEntities.Add(new ItemTagJoinEntity()
        {
          TagId = tagId,
          ItemId = item.ItemId
        });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = item.ItemId });
    }

    [HttpPost]
    public ActionResult DeleteItemTagJoinEntity(int itemTagJoinEntityId)
    {
      ItemTagJoinEntity join = _db.ItemTagJoinEntities.FirstOrDefault(entry => entry.ItemTagJoinEntityId == itemTagJoinEntityId);
      _db.ItemTagJoinEntities.Remove(join);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

CollectionsManager/Views/Collections/Create.cshtml
@{
  ViewData["Title"] = "Add Collection";
}
@model CollectionsManager.Models.Collection
<div class="editForm">
  <h4>Add a new collection</h4>
  @using (Html.BeginForm())
  {
    @Html.TextBoxFor(model => model.Name, new { placeholder = "Name" })
    <br>
    @Html.TextBoxFor(model => model.Description, new { placeholder = "Description" })
    <br>
    <input type="submit" value="Add new collection" />
  }
</div>

CollectionsManager/Views/Collections/Delete.cshtml
@model CollectionsManager.Models.Collection

@{
  ViewData["Title"] = $"Delete {Html.DisplayNameFor(model => model.Name)}";
}
<img class="futureGif" src="https://gifdb.com/images/high/loop-futuristic-retro-wave-grid-mk8j412gtwq7smw2.gif"
  alt="future gif">
<div class="editForm">
  <h3>Are you sure you want to delete this collection?</h3>

  @Html.DisplayFor(model => model.Name)
  @using (Html.BeginForm())
  {
    <input type="submit" value="Delete" />
  }
</div>

CollectionsManager/Views/Collections/Details.cshtml
@model CollectionsManager.Models.Collection
@using CollectionsManager.Models

@{
  ViewData["Title"] = $"{Html.DisplayNameFor(model => model.Name)}";
}
<div class="index">
  <h1>@Model.Name</h1>
  <hr />

  <form asp-controller="Collections" asp-action="Details">
    <input type="hidden" name="collectionId" value="@ViewBag.CollectionId" />
    <p>
      <input type="text" name="SearchString" placeholder="search" value="@ViewBag.SearchString" />
      <input type="submit" value="Filter" />
    </p>
  </form>

  @if (@Model.Items.Count == 0)
  {
    <h3>No items have been added to this collection yet!</h3>
  }
  else
  {
    @foreach (Item item in Model.Items)
    {
      <div class="listRow">
        <img class="thumbnail" src=@item.ImageUrl alt="thumbnail">
        <h3>@Html.ActionLink($"{item.Name}", "Details", "Items", new { id = item.ItemId })</h3>
      </div>
    }
  }
  <h3>Value: $@ViewBag.Sum</h3>
  <div class="detailsIcons">
    <a href="/items/create/">
      <img class="addIcon" src="~/assets/images/addIcon.png" alt="edit icon" />
    </a>
    <a href="/collections/edit/@Model.CollectionId">
      <img class="editIcon" src="~/assets/images/edit.svg" alt="edit icon" />
    </a>
    <a href="/collections/delete/@Model.CollectionId">
      <img class="deleteIcon" src="~/assets/images/deleteIcon.svg" alt="delete icon" />
    </a>
  </div>
</div>

CollectionsManager/Views/Collections/Edit.cshtml
@model CollectionsManager.Models.Collection
<div class="editForm">
  <h4>Editing: @Html.DisplayFor(model => model.Name)</h4>

  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.CollectionId)

    @Html.EditorFor(model => model.Name, new { placeholder = "Name" })

    <input type="submit" value="Save" />
  }
</div>

CollectionsManager/Views/Collections/Index.cshtml
@using CollectionsManager.Models;
<div class="index">
  <div>
    <h1>Collections</h1>
    <div class="form-row">
      <form class="form-row" asp-controller="Collections" asp-action="Index">
        <input class="input" type="text" name="SearchString" placeholder="search" style="padding-right: 50px;" />
        <button class="button" type="submit" style="position: relative; margin-left: -50px;">Filter</button>
      </form>
      <a class="button" asp-controller="Collections" asp-action="Create">New Collection</a>
    </div>
  </div>
  <hr />
  @if (@Model.Count == 0)
  {
    <h3>No collections have been added...</h3>
  }

  @foreach (Collection collection in Model)
  {
    <h3>@Html.ActionLink($"{@collection.Name}", "Details", new { id = collection.CollectionId })</h3>
  }
</div>